### ISSUE TITLE
Recruit AI script not working

### ISSUE THREAD

**Issue by TandelK** [xBloodshed/ITGC-ALiVE.Takistan#4]
Recruiting AI Script is not working properly. Give some errors for the first time.

**Comment by xBloodshed** [comment]
what's the errors coming up?

**Comment by TandelK** [comment]
![2015-08-04_00001](https://cloud.githubusercontent.com/assets/13623158/9066396/f897ebfe-3af4-11e5-927e-5101c09068fc.jpg)

**Comment by xBloodshed** [comment]
Fixed, checked and working.
